### ISSUE TITLE
process-etopo1-data/main.sh is missing

### ISSUE THREAD

**Issue by MoritzStefaner** [fabianehmel/haacker#1] opened 2019-04-10 13:10 UTC
```
npm run process-etopo1-data
. master$ npm run process-etopo1-data

> haaker@1.0.0 process-etopo1-data /Users/mo/Documents/dev/haacker
> sh process-etopo1-data/main.sh

sh: process-etopo1-data/main.sh: No such file or directory
```

**Comment by fabianehmel** [comment] 2019-04-10 18:22
Thanks for reporting, Moritz!

The bug was caused by a wrongly configured .gitignore and is resolved with commit a0ac638d5f688918908971cfc7862cf42537ce70

**Closed as completed by fabianehmel** 2019-04-10 18:22 UTC
